from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .h3_picture_reference_edit import (
    NODE_CLASS_MAPPINGS as _H3_PICTURE_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _H3_PICTURE_NAMES,
)
from .character_pack import (
    NODE_CLASS_MAPPINGS as _CHARACTER_PACK_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _CHARACTER_PACK_NAMES,
)

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **_H3_PICTURE_CLASSES, **_CHARACTER_PACK_CLASSES}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **_H3_PICTURE_NAMES, **_CHARACTER_PACK_NAMES}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
